In [ ]:
#a. Импортируйте библиотеку NumPy
import numpy as np

In [ ]:
#b. Создайте массив из 10 нулей
[0] * 10

[0, 0, 0, 0, 0, 0, 0, 0, 0, 0]

In [ ]:
#c. Создать массив из 10 единиц
[5] * 10

[5, 5, 5, 5, 5, 5, 5, 5, 5, 5]

In [ ]:
#d. Создать массив из 10 пятерок
[x for x in range(10,51)]

[10,
 11,
 12,
 13,
 14,
 15,
 16,
 17,
 18,
 19,
 20,
 21,
 22,
 23,
 24,
 25,
 26,
 27,
 28,
 29,
 30,
 31,
 32,
 33,
 34,
 35,
 36,
 37,
 38,
 39,
 40,
 41,
 42,
 43,
 44,
 45,
 46,
 47,
 48,
 49,
 50]

In [ ]:
#e. Создать массив из целых чисел от 10 до 50
[x for x in range(10, 51) if x % 2 == 0]

[10,
 12,
 14,
 16,
 18,
 20,
 22,
 24,
 26,
 28,
 30,
 32,
 34,
 36,
 38,
 40,
 42,
 44,
 46,
 48,
 50]

In [ ]:
#f. Создать массив из четных чисел от 10 до 50
[[x + 3 * y for x in range(3)] for y in range(3)]

[[0, 1, 2], [3, 4, 5], [6, 7, 8]]

In [ ]:
#g. Создать матрицу 3х3 с числами от 0 до 8
[[x + 3 * y for x in range(3)] for y in range(3)]

[[0, 1, 2], [3, 4, 5], [6, 7, 8]]

In [ ]:
#h. Создать единичную матрицу 3x3
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [ ]:
#i. Используйте NumPy для генерации случайного числа от 0 до 1
np.random.sample()

0.03902753775687595

In [ ]:
#j. Используйте NumPy для генерации массива из 25 случайных чисел,взятых из стандартного нормального распределения
np.random.randn(25)

array([-7.45611003e-04, -1.21923387e-02, -4.65431315e-01, -1.72496458e+00,
       -3.48130481e-01, -1.07142167e+00,  4.03736837e-01,  6.10402476e-01,
       -1.72651148e-01, -1.56428827e+00,  3.39214622e-01,  6.85630408e-01,
        2.67473935e-01,  4.80615127e-01, -1.06297335e+00, -6.51243728e-01,
       -3.52708553e-01,  7.09899222e-02,  8.31366817e-01, -7.18360908e-01,
        1.07234676e+00, -1.06426061e-01,  3.30717516e-01, -1.24656467e+00,
       -2.91596817e-01])

In [ ]:
#k. Создайте следующую матрицу используя функции библиотеки NumPy
np.arange(0.01, 1.01, 0.01).reshape(10, 10)
mat = np.arange(1, 26).reshape(5, 5)

In [ ]:
mat = np.arange(1, 26).reshape(5, 5)

In [ ]:
#l.Необходимо написать код который вернет следующую матрицуиз стартовой
mat[2:, 1:]

array([[12, 13, 14, 15],
       [17, 18, 19, 20],
       [22, 23, 24, 25]])

In [ ]:
#m. Написать код обращения к элементу который вернет значение  20 изстартовой матрицы задачи l.
mat[3, -1]

20

In [ ]:
#n. Написать код к стартовой матрице задачи l , который воспроизводитвывод
mat[4]

array([21, 22, 23, 24, 25])

In [ ]:
#o. Написать код к стартовой матрице задачи l , который воспроизводитвывод
mat[4]

array([21, 22, 23, 24, 25])

In [ ]:
#p. Написать код к стартовой матрице задачи l , который воспроизводитвывод
mat[3:]

array([[16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

In [ ]:
#q. Получить сумму всех значений в стартовой матрице mat
np.sum(mat)

325

In [ ]:
#r. Получить стандартное отклонение в стартовой матрице matnp.sum(mat, axis=0)
np.std(mat)

7.211102550927978

In [ ]:
#s. Получить сумму значений в колонках в стартовой матрице mat
np.sum(mat, axis=0)

array([55, 60, 65, 70, 75])